-- ============================================================================
-- 0001_schema.sql — Monopoly 3D multiplayer MVP: core tables
--
-- Apply order: 0001_schema.sql -> 0002_rls.sql -> 0003_rpc.sql
-- (via MCP apply_migration, one file per call, in this order)
--
-- Seat/player mapping invariant (relied on by the game-action Edge Function):
--   room_players.seat_index === GameState.players[i].id (players are created
--   in seat order at START_GAME; seats are compacted to 0..n-1 right before
--   the game starts).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- profiles — one row per auth user (anonymous sign-in supported)
-- ----------------------------------------------------------------------------
create table public.profiles (
    id           uuid primary key references auth.users (id) on delete cascade,
    display_name text not null check (char_length(display_name) between 1 and 32),
    games_won    int  not null default 0,
    created_at   timestamptz default now()
);

comment on table public.profiles is 'Public player profile; games_won is service-role-maintained.';

-- ----------------------------------------------------------------------------
-- rooms — a lobby/game room, discoverable by 6-char code
-- ----------------------------------------------------------------------------
create table public.rooms (
    id          uuid primary key default gen_random_uuid(),
    code        char(6) not null unique,
    host_id     uuid not null references auth.users (id),
    status      text not null default 'lobby'
                check (status in ('lobby', 'playing', 'finished')),
    max_players int not null default 4 check (max_players between 2 and 4),
    created_at  timestamptz default now()
);

comment on column public.rooms.code is '6 chars from A-Z2-9 (no 0/O/1/I), generated by create_room().';

-- ----------------------------------------------------------------------------
-- room_players — seats in a room (0..3); seat claiming only via RPC
-- ----------------------------------------------------------------------------
create table public.room_players (
    room_id      uuid references public.rooms (id) on delete cascade,
    user_id      uuid references auth.users (id),
    seat_index   int  not null check (seat_index between 0 and 3),
    display_name text not null,
    color_hex    text not null,
    token_kind   text not null default 'pawn',
    is_ready     boolean not null default false,
    joined_at    timestamptz default now(),
    primary key (room_id, user_id),
    unique (room_id, seat_index)
);

-- ----------------------------------------------------------------------------
-- games — one authoritative GameState snapshot per room (jsonb)
-- version is the optimistic-concurrency counter == seq of the last action.
-- ----------------------------------------------------------------------------
create table public.games (
    id            uuid primary key default gen_random_uuid(),
    room_id       uuid not null unique references public.rooms (id) on delete cascade,
    state         jsonb not null,
    version       int not null default 0,
    turn_deadline timestamptz,
    updated_at    timestamptz default now()
);

comment on column public.games.version is 'Optimistic concurrency: update ... where version = expected; seq of last applied action.';
comment on column public.games.turn_deadline is 'Server-clock deadline for the current turn; claim-timeout enforces it.';

-- ----------------------------------------------------------------------------
-- game_actions — append-only authoritative action log (replay/audit)
-- ----------------------------------------------------------------------------
create table public.game_actions (
    id         bigint generated always as identity primary key,
    game_id    uuid not null references public.games (id) on delete cascade,
    seq        int not null,
    seat       int not null,
    action     jsonb not null,
    events     jsonb not null,
    created_at timestamptz default now(),
    unique (game_id, seq)
);

-- ----------------------------------------------------------------------------
-- Indexes
-- rooms(code): already covered by the UNIQUE constraint index (rooms_code_key);
-- a second explicit index would be redundant.
-- ----------------------------------------------------------------------------
create index room_players_user_id_idx on public.room_players (user_id);
create index game_actions_game_id_seq_desc_idx on public.game_actions (game_id, seq desc);

-- ----------------------------------------------------------------------------
-- updated_at maintenance for games
-- ----------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

create trigger games_touch_updated_at
    before update on public.games
    for each row execute function public.touch_updated_at();
