const boardData = [
    { id: 0, name: "BẮT ĐẦU", type: TILE_TYPES.START, color: COLORS.SPECIAL },
    { id: 1, name: "Đ. Nguyễn Huệ", type: TILE_TYPES.PROPERTY, price: 60, rent: 2, color: COLORS.BROWN, groupId: 1, houseCost: 50, houses: 0 },
    { id: 2, name: "Khí Vận", type: TILE_TYPES.CHEST, color: COLORS.SPECIAL },
    { id: 3, name: "Đ. Lê Lợi", type: TILE_TYPES.PROPERTY, price: 60, rent: 4, color: COLORS.BROWN, groupId: 1, houseCost: 50, houses: 0 },
    { id: 4, name: "Thuế Thu Nhập", type: TILE_TYPES.TAX, price: 200, color: COLORS.TAX },
    { id: 5, name: "Ga Sài Gòn", type: TILE_TYPES.RAILROAD, price: 200, rent: 25, color: COLORS.RAIL },
    { id: 6, name: "Đ. Hai Bà Trưng", type: TILE_TYPES.PROPERTY, price: 100, rent: 6, color: COLORS.LBLUE, groupId: 2, houseCost: 50, houses: 0 },
    { id: 7, name: "Cơ Hội", type: TILE_TYPES.CHANCE, color: COLORS.SPECIAL },
    { id: 8, name: "Đ. Điện Biên Phủ", type: TILE_TYPES.PROPERTY, price: 100, rent: 6, color: COLORS.LBLUE, groupId: 2, houseCost: 50, houses: 0 },
    { id: 9, name: "Đ. Võ Thị Sáu", type: TILE_TYPES.PROPERTY, price: 120, rent: 8, color: COLORS.LBLUE, groupId: 2, houseCost: 50, houses: 0 },
    { id: 10, name: "THĂM TÙ", type: TILE_TYPES.JAIL, color: COLORS.SPECIAL },
    { id: 11, name: "Phố Cổ Hội An", type: TILE_TYPES.PROPERTY, price: 140, rent: 10, color: COLORS.PINK, groupId: 3, houseCost: 100, houses: 0 },
    { id: 12, name: "Công Ty Điện", type: TILE_TYPES.UTILITY, price: 150, rent: 20, color: COLORS.UTIL },
    { id: 13, name: "Đại Nội Huế", type: TILE_TYPES.PROPERTY, price: 140, rent: 10, color: COLORS.PINK, groupId: 3, houseCost: 100, houses: 0 },
    { id: 14, name: "Cầu Rồng", type: TILE_TYPES.PROPERTY, price: 160, rent: 12, color: COLORS.PINK, groupId: 3, houseCost: 100, houses: 0 },
    { id: 15, name: "Ga Đà Nẵng", type: TILE_TYPES.RAILROAD, price: 200, rent: 25, color: COLORS.RAIL },
    { id: 16, name: "Đ. Trần Phú", type: TILE_TYPES.PROPERTY, price: 180, rent: 14, color: COLORS.ORANGE, groupId: 4, houseCost: 100, houses: 0 },
    { id: 17, name: "Khí Vận", type: TILE_TYPES.CHEST, color: COLORS.SPECIAL },
    { id: 18, name: "Đ. Bạch Đằng", type: TILE_TYPES.PROPERTY, price: 180, rent: 14, color: COLORS.ORANGE, groupId: 4, houseCost: 100, houses: 0 },
    { id: 19, name: "Đ. Hùng Vương", type: TILE_TYPES.PROPERTY, price: 200, rent: 16, color: COLORS.ORANGE, groupId: 4, houseCost: 100, houses: 0 },
    { id: 20, name: "BÃI ĐẬU XE", type: TILE_TYPES.PARKING, color: COLORS.SPECIAL },
    { id: 21, name: "Đ. Tràng Tiền", type: TILE_TYPES.PROPERTY, price: 220, rent: 18, color: COLORS.RED, groupId: 5, houseCost: 150, houses: 0 },
    { id: 22, name: "Cơ Hội", type: TILE_TYPES.CHANCE, color: COLORS.SPECIAL },
    { id: 23, name: "Đ. Hàng Bài", type: TILE_TYPES.PROPERTY, price: 220, rent: 18, color: COLORS.RED, groupId: 5, houseCost: 150, houses: 0 },
    { id: 24, name: "Đ. Đinh Tiên Hoàng", type: TILE_TYPES.PROPERTY, price: 240, rent: 20, color: COLORS.RED, groupId: 5, houseCost: 150, houses: 0 },
    { id: 25, name: "Ga Hà Nội", type: TILE_TYPES.RAILROAD, price: 200, rent: 25, color: COLORS.RAIL },
    { id: 26, name: "Hồ Gươm", type: TILE_TYPES.PROPERTY, price: 260, rent: 22, color: COLORS.YELLOW, groupId: 6, houseCost: 150, houses: 0 },
    { id: 27, name: "Đ. Lê Thái Tổ", type: TILE_TYPES.PROPERTY, price: 260, rent: 22, color: COLORS.YELLOW, groupId: 6, houseCost: 150, houses: 0 },
    { id: 28, name: "Công Ty Nước", type: TILE_TYPES.UTILITY, price: 150, rent: 20, color: COLORS.UTIL },
    { id: 29, name: "Đ. Bà Triệu", type: TILE_TYPES.PROPERTY, price: 280, rent: 24, color: COLORS.YELLOW, groupId: 6, houseCost: 150, houses: 0 },
    { id: 30, name: "VÀO TÙ", type: TILE_TYPES.GOTOJAIL, color: COLORS.SPECIAL },
    { id: 31, name: "Đ. Đồng Khởi", type: TILE_TYPES.PROPERTY, price: 300, rent: 26, color: COLORS.GREEN, groupId: 7, houseCost: 200, houses: 0 },
    { id: 32, name: "Đ. Tôn Đức Thắng", type: TILE_TYPES.PROPERTY, price: 300, rent: 26, color: COLORS.GREEN, groupId: 7, houseCost: 200, houses: 0 },
    { id: 33, name: "Khí Vận", type: TILE_TYPES.CHEST, color: COLORS.SPECIAL },
    { id: 34, name: "Lăng Bác", type: TILE_TYPES.PROPERTY, price: 320, rent: 28, color: COLORS.GREEN, groupId: 7, houseCost: 200, houses: 0 },
    { id: 35, name: "Sân Bay Nội Bài", type: TILE_TYPES.RAILROAD, price: 200, rent: 25, color: COLORS.RAIL },
    { id: 36, name: "Cơ Hội", type: TILE_TYPES.CHANCE, color: COLORS.SPECIAL },
    { id: 37, name: "Bitexco", type: TILE_TYPES.PROPERTY, price: 350, rent: 35, color: COLORS.DBLUE, groupId: 8, houseCost: 200, houses: 0 },
    { id: 38, name: "Thuế Hàng Hiệu", type: TILE_TYPES.TAX, price: 100, color: COLORS.TAX },
    { id: 39, name: "Landmark 81", type: TILE_TYPES.PROPERTY, price: 400, rent: 50, color: COLORS.DBLUE, groupId: 8, houseCost: 200, houses: 0 }
];

boardData.forEach(tile => { if (tile.type === TILE_TYPES.PROPERTY || tile.type === TILE_TYPES.RAILROAD || tile.type === TILE_TYPES.UTILITY) tile.owner = null; });
window.boardData = boardData;
